# Generated by Django 3.2.11 on 2022-02-14 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sweet',
        ),
    ]
