# Generated by Django 3.2.11 on 2022-02-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_bakers', '0003_home_tb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home_tb',
            old_name='Usernames',
            new_name='Businessname',
        ),
        migrations.AddField(
            model_name='home_tb',
            name='Aadharcard',
            field=models.ImageField(default=2, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home_tb',
            name='Address',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='home_tb',
            name='Businesstype',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='home_tb',
            name='Pannumber',
            field=models.CharField(default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='home_tb',
            name='Phone',
            field=models.CharField(default='none', max_length=10),
        ),
    ]
