# Generated by Django 3.2.11 on 2022-02-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_bakers', '0004_auto_20220221_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_tb',
            name='Aadharcard',
            field=models.ImageField(upload_to='img'),
        ),
    ]
