# Generated by Django 3.2.11 on 2022-02-25 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_bakers', '0005_alter_home_tb_aadharcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='categ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('desc', models.TextField()),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('img', models.ImageField(upload_to='product')),
                ('available', models.BooleanField(default='True')),
                ('BakeryId', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='home_bakers.home_tb')),
                ('category', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='home_bakers.categ')),
            ],
        ),
    ]
