# Generated by Django 3.2.11 on 2022-02-28 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_bakers', '0006_categ_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(default='delivery_boy.jpg', upload_to='product'),
        ),
    ]
