# Generated by Django 3.2.11 on 2022-03-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_bakers', '0007_alter_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_tb',
            name='Businessimage',
            field=models.ImageField(default='none', upload_to='img'),
        ),
    ]
