# Generated by Django 3.2.10 on 2022-03-09 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_bakers', '0008_home_tb_businessimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Products',
        ),
    ]
