# Generated by Django 4.0.3 on 2022-04-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_bakers', '0009_rename_product_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_tb',
            name='Pannumber',
            field=models.CharField(default='none', max_length=12),
        ),
    ]
