# Generated by Django 4.0.3 on 2022-04-01 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_bakers', '0011_remove_products_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='categ',
            name='BakeryId',
            field=models.ForeignKey(default='8', on_delete=django.db.models.deletion.CASCADE, to='home_bakers.home_tb'),
        ),
    ]
