# Generated by Django 3.2.10 on 2022-04-08 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_bakers', '0012_categ_bakeryid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categ',
            name='BakeryId',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='home_bakers.home_tb'),
        ),
    ]
