# Generated by Django 3.2.11 on 2022-02-17 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_boy', '0003_delivery_tb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='delivery_tb',
        ),
    ]
