# Generated by Django 3.2.11 on 2022-02-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery_boy', '0004_delete_delivery_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery_Tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=50)),
                ('Lastname', models.CharField(max_length=50)),
                ('Usernames', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Password', models.CharField(max_length=10)),
            ],
        ),
    ]
