# Generated by Django 3.2.11 on 2022-03-07 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_boy', '0006_auto_20220223_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_tb',
            name='Businessimage',
            field=models.ImageField(default='none', upload_to='img'),
        ),
    ]
