# Generated by Django 4.0.3 on 2022-03-18 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_shop', '0011_bakery_tb_businessimage'),
        ('home_bakers', '0009_rename_product_products'),
        ('user', '0015_auto_20220310_1217'),
        ('delivery_boy', '0009_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='bakey',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='bakery_shop.bakery_tb'),
        ),
        migrations.AddField(
            model_name='notification',
            name='home',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='home_bakers.home_tb'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='user.user_tb'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='order',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
