# Generated by Django 4.0.3 on 2022-03-18 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_boy', '0010_notification_bakey_notification_home_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='order',
            new_name='neworderstatus',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='status',
            new_name='orderStatus',
        ),
    ]
