# Generated by Django 3.2.10 on 2022-04-08 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20220310_1217'),
        ('home_bakers', '0013_alter_categ_bakeryid'),
        ('bakery_shop', '0014_categ_bakeryid'),
        ('delivery_boy', '0011_rename_order_notification_neworderstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='bakey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bakery_shop.bakery_tb'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='boy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery_boy.delivery_tb'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='home',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home_bakers.home_tb'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user_tb'),
        ),
    ]
