# Generated by Django 3.2.11 on 2022-02-22 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_shop', '0003_bakery_tb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bakery_tb',
            old_name='Usernames',
            new_name='Businessname',
        ),
        migrations.AddField(
            model_name='bakery_tb',
            name='Address',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='bakery_tb',
            name='Businesstype',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='bakery_tb',
            name='Pannumber',
            field=models.CharField(default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='bakery_tb',
            name='Phone',
            field=models.CharField(default='none', max_length=10),
        ),
    ]
