# Generated by Django 3.2.11 on 2022-02-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_shop', '0004_auto_20220222_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakery_tb',
            name='Aadharcard',
            field=models.ImageField(default=1, upload_to='img'),
            preserve_default=False,
        ),
    ]
