# Generated by Django 3.2.11 on 2022-02-25 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_shop', '0006_categ_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='BakeryId',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='bakery_shop.bakery_tb'),
            preserve_default=False,
        ),
    ]
