# Generated by Django 3.2.11 on 2022-02-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_shop', '0007_product_bakeryid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.BooleanField(default='True'),
        ),
    ]
