# Generated by Django 3.2.11 on 2022-02-25 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_shop', '0008_product_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='BakeryId',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='bakery_shop.bakery_tb'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='bakery_shop.categ'),
        ),
    ]
