# Generated by Django 3.2.11 on 2022-02-26 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_shop', '0009_auto_20220225_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(default='delivery_boy.jpg', upload_to='product'),
        ),
    ]
