# Generated by Django 4.0.3 on 2022-04-01 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_shop', '0011_bakery_tb_businessimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bakery_tb',
            name='Pannumber',
            field=models.CharField(default='none', max_length=12),
        ),
    ]
