# Generated by Django 4.0.3 on 2022-04-01 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_shop', '0012_alter_bakery_tb_pannumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
