# Generated by Django 4.0.3 on 2022-04-01 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_shop', '0013_remove_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='categ',
            name='BakeryId',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='bakery_shop.bakery_tb'),
        ),
    ]
