# Generated by Django 3.2.11 on 2022-02-17 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_demo_user_tb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_tb',
            old_name='conformpassword',
            new_name='ConformPassword',
        ),
        migrations.RenameField(
            model_name='user_tb',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='user_tb',
            old_name='password',
            new_name='Password',
        ),
        migrations.RenameField(
            model_name='user_tb',
            old_name='usernames',
            new_name='Usernames',
        ),
    ]
