# Generated by Django 3.2.11 on 2022-02-17 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20220217_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_tb',
            name='ConformPassword',
        ),
    ]
