# Generated by Django 3.2.11 on 2022-02-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_tb_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_tb',
            name='Address',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='user_tb',
            name='Phone',
            field=models.CharField(default='none', max_length=10),
        ),
    ]
