# Generated by Django 3.2.11 on 2022-03-07 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_tb_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_tb',
            name='Userimage',
            field=models.ImageField(default='none', upload_to='img'),
        ),
    ]
