# Generated by Django 3.2.10 on 2022-03-09 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20220309_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 3, 9, 23, 30, 58, 430318)),
        ),
    ]
