# Generated by Django 3.2.10 on 2022-03-10 06:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_shop', '0011_bakery_tb_businessimage'),
        ('home_bakers', '0009_rename_product_products'),
        ('user', '0014_auto_20220310_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='BCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('image', models.ImageField(default='none', upload_to='img')),
                ('pname', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('status', models.BooleanField(default='False')),
                ('bakers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakery_shop.bakery_tb')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user_tb')),
            ],
        ),
        migrations.CreateModel(
            name='HCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('image', models.ImageField(default='none', upload_to='img')),
                ('pname', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('status', models.BooleanField(default='False')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_bakers.home_tb')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user_tb')),
            ],
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
