# Generated by Django 3.2.10 on 2022-04-10 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20220310_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='bcart',
            name='paystatus',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='hcart',
            name='paystatus',
            field=models.BooleanField(default='False'),
        ),
    ]
